// next.config.js
const nextConfig = {
  output: 'export',
  basePath: '/finance', // Replace 'finance' with your repository name
  assetPrefix: '/finance/', // Replace 'finance' with your repository name
  images: {
    unoptimized: true,
  },
  // ... any other config
};
export default nextConfig;
